### ISSUE TITLE
Move from Parse to MongoDB

### ISSUE THREAD

**Issue by golf1052** [golf1052/Attention_Passengers#1]
Parse [shut down](http://blog.parse.com/announcements/moving-on/) a little while ago. This app currently uses Parse as a backend so it needs to be ported to use MongoDB instead. I considered doing just a migration to parse-server but it apparently only supports 2.6.X and 3.0.X and my server is running 3.2 so moving fully from Parse is probably better and "easier".

**Comment by zdhickman** [comment]
can i get an update on this

**Comment by golf1052** [comment]
Still an open issue. The favorite routes feature was never fully implemented and that was what really required a DB backend. I'll probably get around to this at some point (read it may be a year+) but feel free to start working on this if you want. The service is still up and running.

**Comment by golf1052** [comment]
Closing this issue as this project is no longer in active development.

Using the work active loosely 😛

**Comment by zdhickman** [comment]
but k is nowhere near d
